name: Build and Publish Ansible EE

on:
  push:
    branches:
      - main
      - develop
    tags:
      - 'v*'
  pull_request:
    branches:
      - main
      - develop
  workflow_dispatch:
    inputs:
      push_image:
        description: 'Push image to registry'
        required: false
        default: true
        type: boolean
      version:
        description: 'Semantic version to use for tagging (without v prefix)'
        required: false
        type: string
      version_tag:
        description: 'Full version tag (with v prefix)'
        required: false
        type: string
  workflow_call:
    inputs:
      version:
        description: 'Semantic version to use for tagging (without v prefix)'
        required: false
        type: string
      version_tag:
        description: 'Full version tag (with v prefix)'
        required: false
        type: string

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  # Job to setup common resources and extract metadata
  setup:
    runs-on: ubuntu-latest
    outputs:
      tags: ${{ steps.meta.outputs.tags }}
      labels: ${{ steps.meta.outputs.labels }}
      json: ${{ steps.meta.outputs.json }}
      version: ${{ inputs.version }}
      version_tag: ${{ inputs.version_tag }}
      image_name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      build_tag: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:build-${{ github.run_number }}
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=raw,value=latest,enable={{is_default_branch}}
            type=sha,prefix={{branch}}-
            type=raw,value=${{ inputs.version }},enable=${{ inputs.version != '' }}
            type=raw,value=${{ inputs.version_tag }},enable=${{ inputs.version_tag != '' }}

  # Job to build the execution environment
  build:
    runs-on: ubuntu-latest
    needs: setup
    outputs:
      build_tag: ${{ needs.setup.outputs.build_tag }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install ansible-builder
        run: |
          python -m pip install --upgrade pip
          pip install ansible-builder

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Execution Environment
        run: |
          ansible-builder build \
            --tag ${{ needs.setup.outputs.build_tag }} \
            --container-runtime docker \
            --verbosity 2

      - name: Save image to artifact
        run: |
          mkdir -p /tmp/image
          docker save ${{ needs.setup.outputs.build_tag }} -o /tmp/image/image.tar

      - name: Upload image as artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: /tmp/image/image.tar
          retention-days: 1

  # Job to test the execution environment
  test:
    runs-on: ubuntu-latest
    needs: [setup, build]
    
    steps:
      - name: Download image artifact
        uses: actions/download-artifact@v4
        with:
          name: docker-image
          path: /tmp/image

      - name: Load Docker image
        run: |
          docker load -i /tmp/image/image.tar

      - name: Test Execution Environment
        run: |
          # Test basic functionality
          docker run --rm ${{ needs.setup.outputs.build_tag }} ansible --version
          docker run --rm ${{ needs.setup.outputs.build_tag }} ansible-galaxy --version
          
          # Test that collections are available (if any are specified)
          docker run --rm ${{ needs.setup.outputs.build_tag }} ansible-galaxy collection list

  # Job to scan the image for vulnerabilities
  scan:
    runs-on: ubuntu-latest
    needs: [setup, build]
    permissions:
      contents: read
      security-events: write
      
    steps:
      - name: Download image artifact
        uses: actions/download-artifact@v4
        with:
          name: docker-image
          path: /tmp/image

      - name: Load Docker image
        run: |
          docker load -i /tmp/image/image.tar

      - name: Cache Trivy DB
        uses: actions/cache@v4
        with:
          path: .cache/trivy
          key: cache-trivy-${{ github.run_id }}
          restore-keys: |
            cache-trivy-

      - name: Scan image for vulnerabilities
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ needs.setup.outputs.build_tag }}
          format: 'sarif'
          output: 'trivy-results.sarif'
          cache-dir: .cache/trivy

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        if: always() && (github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository)
        with:
          sarif_file: 'trivy-results.sarif'
          category: 'trivy'
        continue-on-error: true

  # Job to generate SBOM for the image
  sbom:
    runs-on: ubuntu-latest
    needs: [setup, build]
    if: github.event_name != 'pull_request'
    
    steps:
      - name: Download image artifact
        uses: actions/download-artifact@v4
        with:
          name: docker-image
          path: /tmp/image

      - name: Load Docker image
        run: |
          docker load -i /tmp/image/image.tar

      - name: Generate SBOM
        uses: anchore/sbom-action@v0
        with:
          image: ${{ needs.setup.outputs.build_tag }}
          format: spdx-json
          output-file: sbom.spdx.json

      - name: Upload SBOM as artifact
        uses: actions/upload-artifact@v4
        with:
          name: sbom
          path: sbom.spdx.json

  # Job to push the image to the registry
  publish:
    runs-on: ubuntu-latest
    needs: [setup, build, test, scan]
    if: github.event_name != 'pull_request' && (github.event_name != 'workflow_dispatch' || inputs.push_image)
    permissions:
      contents: read
      packages: write
      
    steps:
      - name: Download image artifact
        uses: actions/download-artifact@v4
        with:
          name: docker-image
          path: /tmp/image

      - name: Load Docker image
        run: |
          docker load -i /tmp/image/image.tar

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Tag and push images to GHCR
        run: |
          # Tag the built image with all metadata tags
          echo "${{ needs.setup.outputs.tags }}" | while read -r tag; do
            echo "Tagging: $tag"
            docker tag ${{ needs.setup.outputs.build_tag }} "$tag"
            echo "Pushing: $tag"
            docker push "$tag"
          done
          
          # Add specific semantic version tags if provided
          if [ -n "${{ needs.setup.outputs.version }}" ]; then
            echo "Adding semantic version tags..."
            
            # Create semver-style tags (major.minor.patch, major.minor, major)
            VERSION="${{ needs.setup.outputs.version }}"
            MAJOR=$(echo $VERSION | cut -d. -f1)
            MINOR=$(echo $VERSION | cut -d. -f2)
            
            echo "Tagging: ${{ needs.setup.outputs.image_name }}:$VERSION"
            docker tag ${{ needs.setup.outputs.build_tag }} "${{ needs.setup.outputs.image_name }}:$VERSION"
            docker push "${{ needs.setup.outputs.image_name }}:$VERSION"
            
            echo "Tagging: ${{ needs.setup.outputs.image_name }}:$MAJOR.$MINOR"
            docker tag ${{ needs.setup.outputs.build_tag }} "${{ needs.setup.outputs.image_name }}:$MAJOR.$MINOR"
            docker push "${{ needs.setup.outputs.image_name }}:$MAJOR.$MINOR"
            
            echo "Tagging: ${{ needs.setup.outputs.image_name }}:$MAJOR"
            docker tag ${{ needs.setup.outputs.build_tag }} "${{ needs.setup.outputs.image_name }}:$MAJOR"
            docker push "${{ needs.setup.outputs.image_name }}:$MAJOR"
            
            # Always update latest on semantic release
            echo "Tagging: ${{ needs.setup.outputs.image_name }}:latest"
            docker tag ${{ needs.setup.outputs.build_tag }} "${{ needs.setup.outputs.image_name }}:latest"
            docker push "${{ needs.setup.outputs.image_name }}:latest"
          fi
          
          echo "Successfully pushed to GitHub Container Registry:"
          echo "Repository: ${{ needs.setup.outputs.image_name }}"
          echo "Available at: https://github.com/${{ github.repository }}/pkgs/container/$(basename ${{ env.IMAGE_NAME }})"
